name: CI

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:

  test-go-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21', '1.22' ]
    name: Go ${{ matrix.go }} Test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -v --cover ./...
